### ISSUE TITLE
Markdown syntax

### ISSUE THREAD

**Issue by Yimiprod** [marvinhagemeister/vscode-theme-afterglow-remastered#2]
At the moment there's no support at all for markdown.

**Comment by marvinhagemeister** [comment]
Thanks for spotting this! Although I do edit `.md` files every now and then, I haven't noticed the lack of syntax highlighting. Now that vscode supports a much more developer friendly way to create theme files, I'm planning on converting the code to the new format. Supporting markdown with the next release will make a nice addition 💯
